### ISSUE TITLE
enhance.dev rework

### ISSUE THREAD

**Issue by shaedrich** [brianleroux/wtfjs#168]
### Todo:
- [x] `/` currently redirects to `/wtfs`. That's not the current behavior
- [x] `/wtfs` works but `/wtfs` doesn't. That's not the current behavior
- [x] about and license page

### Open questions
- [ ] jQuery still needed? _I can't find any place, where it is used_
- [ ] Should the design stay the same or be brought up to date?
- [ ] Should `shared/` logic be preserved?
